### ISSUE TITLE
filename comparison for fxcop results not matching

### ISSUE THREAD

**Issue by doogie2301** [tomasbjerre/violation-comments-to-stash-plugin#9]
It appears that the files are not matching between the Stash pull request and the FxCop results due to the path separator (forward slash vs backslash).  For example, the file is reported from Stash as [path]/[filename] while the FxCop results report it as [path]\[filename]

**Comment by tomasbjerre** [comment]
Can you supply an example fxcop-reports file?

**Comment by tomasbjerre** [comment]
I'm releasing 1.6 now where back-slashes in paths are replaced by forward-slashes. That may solve this issue. I would still like to have a sample reports-file from FxCop so that I can add a test case for it.

**Comment by doogie2301** [comment]
Sure, I can provide a sample fxcop report file.  I'm kind of new to GitHub though, and I don't see a way to attach a file here.

**Comment by tomasbjerre** [comment]
Ok you can email it to me if you like: tomas.bjerre85@gmail.com
